Removed foundation & FA dependency, used CSS Grid
uq-its-ss/design-system pull request #107
Opened 2020-10-22 05:34 UTC by uqtgeor4

2020-10-23 04:32 UTC, uqmchu requested changes
Hey,

Overall, good work! We're just missing prefixing, & documentation (which means the actual stories need adjusting as well). When the prefixing is done, the kitchen sink and private design output examples need updating as well.

I've also removed the Foundation block-grid package and adjusted the icon positioning and colour.

Cheers

2020-10-25 23:31 UTC, uqtgeor4 commented on packages/grid-menu/src/scss/_component.scss
>  .grid-menu {
Prefixing done. Documentation added

2020-10-25 23:42 UTC, uqtgeor4 commented on packages/grid-menu/src/scss/_component.scss
>  .grid-menu {
Kitchen sink updated

2020-10-26 03:03 UTC, uqmchu commented
Push some changes to tidy up docs and fix a JS method all.

2020-10-26 03:04 UTC, uqmchu approved these changes

2020-10-26 03:04 UTC, merged