Itsadssd 30861 fix consistency issues across components
uq-its-ss/design-system pull request #173
Opened 2021-03-08 06:10 UTC by uqtgeor4

Done below points
**General**
- Remove old images (e.g. http://lorempixel.com/1920/1080/)
- Changed @use '@uqds/core/src/scss/global' as core; to @use '@uqds/core/src/scss/global' as *; where possible
- ::before and ::after instead on :before and :after
- "uq-" prefixing for component scss
- Partial rem, px to its corresponding variables for blockquote, button, form comps

**Components**
- Grid-menu: Breakpoints needs to be streamlined and scss BEM naming
- Blockquote: Convert to scss BEM naming

2021-03-12 01:28 UTC, Bcrunk requested changes
Hey Timmy 

Kitchen Sink is now missing a number of the changes you made. 

I think you still need to update the classes there?

2021-03-16 05:04 UTC, Bcrunk requested changes

2021-03-16 05:29 UTC, uqmchu commented on packages/grid-menu/src/scss/_component.scss
>    &__link {
Tidied up the underline (i.e. removed the weird part underline). Hover effect (i.e. changing the background colour) can be achieved by using one of the icon pkg filter constants). There's another example of this being done on the grid-menu package SCSS file itself.

2021-03-16 05:31 UTC, uqmchu commented on packages/grid-menu/src/scss/_component.scss
>    &__link {
You can extend the icon pkg with more filter constants or just add a custom one to the grid-menu pkg with a good reason for either one.

2021-03-18 01:00 UTC, uqtgeor4 commented on packages/button/src/scss/_component.scss
> +  font-size: core.$space;
Done

2021-03-19 05:21 UTC, Bcrunk approved these changes

2021-03-19 05:22 UTC, merged