added variant of hero and adjusted markup naming scheme. additional v…
uq-its-ss/design-system pull request #196
Opened 2021-04-18 22:55 UTC by uqnm

…ariant of large-banner for increased height. fixed content width bug

2021-04-22 06:40 UTC, uqtgeor4 requested changes

2021-04-22 06:40 UTC, uqtgeor4 commented on packages/hero/src/scss/_component.scss
> +        padding-top: 10rem;
replace rems with its equivalent space variables in core.

2021-04-22 06:40 UTC, uqtgeor4 commented on packages/storybook-html/src/components/hero/hero.stories.js
'Feature hero' rather than 'Feature image hero' as Story name (Suggestion)

2021-04-22 06:40 UTC, uqtgeor4 commented on packages/storybook-html/src/components/hero/hero.stories.js
>  };
Remove unwanted commented lines from hero.stories.js

2021-04-22 06:40 UTC, uqtgeor4 commented on packages/storybook-html/src/components/intro/kitchen-sink.html
>  </div>
Update hero.docs.mdx with updated html code. I have done this. Please pull

2021-04-23 04:30 UTC, Bcrunk reviewed
Are you going to include the example (its not technically an exclusive for the homepage right?

2021-07-30 00:25 UTC, closed without merging