28090 accordion uplift
uq-its-ss/design-system pull request #220
Opened 2021-07-14 05:33 UTC by jen-lui

2021-07-15 00:56 UTC, uqnm approved these changes
looks good

2021-07-16 01:55 UTC, Bcrunk reviewed
Should we still specify a default? 

We could still telegraph to users the preferred implementation. 
i.e. if we think the best way of doing it is with lists? (which ever is most accessible and machine radable)

See the "Buttons" example .

2021-07-16 01:58 UTC, Bcrunk reviewed
not sure about the Alternate behaviour being part of how and when to use. 
 
The alternate behaviour is still just a variant and may be better placed there. 

Cards as an example still has everything as a variant.. How and when to use is more about the component usage and less about the variations in functionality?

2021-07-16 02:44 UTC, Bcrunk reviewed
The naming still throws me off, is-manual feel wrong.
I took a look at Material design, they have the functionality fliped but refer to the options as 

Collapsible and Expandable 

I am leaning more towards is-expandable (just my opinion / recommendation, not a red flag)

2021-07-16 03:00 UTC, Bcrunk requested changes

2021-07-16 03:14 UTC, jen-lui commented
> Should we still specify a default?
> 
> We could still telegraph to users the preferred implementation.
> i.e. if we think the best way of doing it is with lists? (which ever is most accessible and machine radable)
> 
> See the "Buttons" example .

For this component, there isn't really a default because the docs provide guidance on which to use depending on the content that needs to be displayed.

2021-07-16 03:19 UTC, jen-lui commented
> not sure about the Alternate behaviour being part of how and when to use.
> 
> The alternate behaviour is still just a variant and may be better placed there.
> 
> Cards as an example still has everything as a variant.. How and when to use is more about the component usage and less about the variations in functionality?

Agree, have moved this from "How and when to use" to a separate section for behaviour and the variant.

2021-07-16 03:21 UTC, jen-lui commented
> The naming still throws me off, is-manual feel wrong.
> I took a look at Material design, they have the functionality fliped but refer to the options as
> 
> Collapsible and Expandable
> 
> I am leaning more towards is-expandable (just my opinion / recommendation, not a red flag)

is-expandable feels odd because all of the accordions are expandable? I've updated the docs so hopefully the distinction is more obvious between default automatic expand/collpase behaviour and variant manual expand/collapse behaviour.

2021-07-16 03:22 UTC, jen-lui commented on packages/accordion/src/scss/_component.scss
> +    font-size: 1.25rem;
Fixed

2021-07-16 05:33 UTC, Bcrunk approved these changes

2021-07-16 05:35 UTC, merged