Itsadssd 29284 component documentation
uq-its-ss/design-system pull request #228
Opened 2021-07-26 01:46 UTC by Bcrunk

2021-07-27 05:49 UTC, jen-lui requested changes

2021-07-29 05:34 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +## Overview
I hate using BR tags to add space ... I might move this to a new story for us to change the settings in storybook.

2021-07-29 05:39 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +## Default example
Updated,

2021-07-29 05:56 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +  <Story id="components-blockquote" />
Updated. 

There is an issue with the height of the canvases, it works automatically in some instances and not in others. I will review and see if i fix here or create a new story for that system wide

2021-07-30 01:27 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +## Variant examples
The initial task was just to correct the structure, I had to stop myself from going further and reworking all the examples, that is covered in the uplift tickets. But I agree and i think some of the examples and variants should be dropped, the Quote variant does not add value.

2021-07-30 01:28 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.stories.js
> +import blockquoteDarkHTML from './blockquote_dark.html';
Do you have an example.. I believe the the underscore is a requirement of storybook not optional in the naming structure.

2021-07-30 01:32 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.stories.js
> +    default: 'Dark'
Agree naming is off for this aspect, I think it needs a significant correction.  I will add notes to the uplift story

2021-07-30 01:33 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +```
I have correct the structure of the existing doc, I did not add in the missing sections but added them to he uplift.

2021-08-01 23:38 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +## Variant examples
added to uplift

2021-08-01 23:40 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +  <Story id="components-blockquote" />
Added a story to review canvas heights in storybook.

2021-08-01 23:51 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.stories.js
> +    default: 'Dark'
added to uplift

2021-08-01 23:52 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +```
added to uplift

2021-08-02 00:53 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +        <p>Words can be like X-rays, if you use them properly — they’ll go through anything. You read and you’re pierced.</p>
added to Uplift sotry

2021-08-02 00:59 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +## Overview
I have added a story into backlog to evaluate system wide.

2021-08-02 01:12 UTC, jen-lui commented on packages/storybook-html/src/components/blockquote/blockquote.stories.js
> +import blockquoteDarkHTML from './blockquote_dark.html';
Table, button, accordion - the HTML files use hyphen

2021-08-02 01:41 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.stories.js
> +import blockquoteDarkHTML from './blockquote_dark.html';
Updated

2021-08-02 01:41 UTC, Bcrunk commented on packages/storybook-html/src/components/blockquote/blockquote.docs.mdx
> +
added to uplift story

2021-08-02 01:44 UTC, jen-lui approved these changes

2021-08-02 01:52 UTC, merged