For discussion header changes
uq-its-ss/design-system pull request #308
Opened 2022-05-13 01:56 UTC by larowlan

2022-05-19 02:42 UTC, Bcrunk requested changes
@larowlan  getting the following error

TypeError: Cannot read properties of undefined (reading 'querySelector')

could only get it working by modifying el.querySelector back to document.querySelector

2022-05-19 02:57 UTC, larowlan commented
Yeah, the calling code needs to pass in an element now

2022-05-23 03:08 UTC, Bcrunk commented
Modified to include (calling code needs to pass in an element now) 

Code appears to work, not sure how appropriate my naming is?

2022-05-24 23:17 UTC, Bcrunk approved these changes

2022-05-25 01:35 UTC, merged