ITSADSSD-59775: Copy button
uq-its-ss/design-system pull request #575
Opened 2024-12-08 23:02 UTC by jptaranto

![Screenshot 2024-12-09 at 9 54 32 am](https://github.com/user-attachments/assets/8690d23b-87eb-43f2-85af-7748242c1c7c)

2024-12-09 00:06 UTC, mstrelan commented on packages/storybook-html/stories/components/copy-button/copy-button.stories.js
I think it would be good to have an example of copying the value of a form element, e.g. a textarea

2024-12-09 05:53 UTC, Bcrunk requested changes
There is a spacing issue on the article page, the button has no spacing between the Alert. 

![Uploading Screenshot 2024-12-09 at 3.52.26 PM.png…]()

2024-12-09 21:05 UTC, jptaranto commented
Hey @Bcrunk spacing is fixed after merging master in.

<img width="835" alt="Screenshot 2024-12-10 at 8 02 15 am" src="https://github.com/user-attachments/assets/70a4edfd-7269-41f7-9bdf-2b93ed64cc6b">

2024-12-09 21:06 UTC, jptaranto commented on packages/storybook-html/stories/components/copy-button/copy-button.stories.js
We didn't have a requirement for it to work this way - it's designed to copy a predetermined string only.

2024-12-09 22:12 UTC, mstrelan commented on packages/storybook-html/stories/components/copy-button/copy-button.stories.js
@jptaranto how do you anticipate that working for the republish functionality? I thought we'd probably have the markup to copy in a hidden textarea. Similar to this example from The Conversation, but the textarea is hidden.

![image](https://github.com/user-attachments/assets/0e04961a-1bbf-431e-918a-874f0de07e48)

2024-12-11 00:20 UTC, jptaranto commented on packages/storybook-html/stories/components/copy-button/copy-button.stories.js
Yeah that would work in this case as it's not editable. But it would probably be easier for it to just be a json encoded data attribute on the button itself.

2024-12-11 00:46 UTC, Bcrunk approved these changes

2024-12-11 00:47 UTC, merged